# One docker-compose to rule them all...
version: '3.7'
services:
  api:
    build:
      context: api
      dockerfile: 'Dockerfile.dev'
    volumes:
      - ./api:/app
    ports:
      - '8080:8080'
    depends_on:
      - api_db

  api_db:
    build:
      context: api
      dockerfile: 'dev_env/postgres.Dockerfile'
    ports:
      - '5430:5432'

  admin:
    build:
      context: react/admin
      dockerfile: 'Dockerfile.dev'
    volumes:
      - ./react/admin:/app
    ports:
      - '5000:3000'

  manager:
    build:
      context: react/manager
      dockerfile: 'Dockerfile.dev'
    volumes:
      - ./react/manager:/app
    ports:
      - '4000:4000'
      - '4001:4001'
