version: "3.7"
services:
  test_api:
    build:
      context: api
      dockerfile: "Dockerfile.test"
    environment:
      - AWS_ACCESS_KEY_ID=AKIASI6VSGJU23DT7ME4
      - AWS_SECRET_ACCESS_KEY=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
    volumes:
      - ./api:/app
    depends_on:
      - test_db
  test_db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_MULTIPLE_DATABASES: resolvers_test,middleware_test
    restart: on-failure
    volumes:
      - ./api/dev_env/test_db_init:/docker-entrypoint-initdb.d/
      - ./api/dev_env/init.sql:/init.sql
