branch-defaults:
  dev:
    environment: react-admin
global:
  application_name: blindfold-ttc
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Docker running on
    64bit Amazon Linux/2.14.2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  workspace_type: Application
