database:
  host: api_db
  user: ttc-api
  password: thd7sds3928dxxkjaKi8
  database: postgresdb
  port: 5432
devAdmin:
  firstName: Dev
  lastName: Admin
  email: admin@admin.com
  password: iamasuperadmin
jwt:
  secret: wKz%rR69b8vX24%RMJ&MpmYxNfRjHPKcfU@yXo#^9@Z9EHZ2eeDp9B818!^Aq7oLTHj!@pjZZlTnbTG6!
  adminExpirationHours: 3 # How many hours until the admin auth token expires
